name: Run Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  NPM_TOKEN: ""

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: -u root
    steps:
      - name: Install GJS
        run: pacman -Sy --noconfirm gjs
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        name: Setup Node.js
        with:
          node-version: 18
      - name: Install dependencies
        run: ./.yarn/yarn.cjs install --frozen-lockfile
      - name: Run TypeScript
        run: ./.yarn/yarn.cjs test:tsc
      - name: Run linter
        run: ./.yarn/yarn.cjs test:lint
      - name: Run prettier
        run: ./.yarn/yarn.cjs test:prettier
      - name: Run build
        run: ./.yarn/yarn.cjs build
      - name: Run unit tests
        run: ./.yarn/yarn.cjs test:unit --ci
